### ISSUE TITLE
.htaccess files are not processed

### ISSUE THREAD

**Issue by pwaring** [skx/templer#25]
I've added a `.htaccess` file to the `input` directory of one of my Templer sites, but when I run the `templer` command it's not copied across in the same way as `*.pdf` files or `robots.txt`. Is this intentional, or is Templer using something like `*.*` to get the files under `input` and therefore missing dotfiles?

**Comment by skx** [comment]
That is not intentional, and is a bug.

The code in `sub assets` in `lib/Templer/Site.pm` is supposed to correctly handle files with leading dots, and has comments to that effect.

A quick test shows things working as I'd expect on a new site:

     shelob ~ $ templer-generate tmp-site
     shelob ~ $ cd tmp-site/

     shelob ~/tmp-site $ touch input/.htaccess
     shelob ~/tmp-site $ templer
     All done: 2 page(s) updated in less than 1 second.

     shelob ~/tmp-site $ ls output/.htaccess 
     output/.htaccess

Similarly one of my existing sites also works correctly.   Is there any chance you could add a verbose setting to lib/Templer/Site.pm at the point it invokes tar, or uses `_findFiles` to see why it is failing for you?  Or share your site content so I can try building it locally?

**Comment by pwaring** [comment]
Terribly sorry, it turned out to be a bug in my deployment script which wasn't picking up dotfiles. I feel a bit silly now. :)

**Comment by skx** [comment]
I understand these things happen somtimes.  Don't feel bad!
