### ISSUE TITLE
Extending the file pattern example

### ISSUE THREAD

**Issue by gh-4** [skx/templer#33]
This is more a question or enhancement request than an issue as such.

I'm trying to do something like

https://steve.fi/Software/templer/examples/complex/output/glob.html

but with a little extra bit.  That is, if the loop is currently at IMAGE2.jpg, can it include a file called say IMAGE2.jpg.caption or IMAGE2-caption.txt or something like that?

Is there a way to do that?

Thanks

**Comment by skx** [comment]
Unfortunately this isn't directly supported.  It is close to being supported, but due to a bug it fails - I'll report that and fix it shortly.

The best I could do is fix the bug, then write this:

         files: file_glob( "*.jpg*" )
         ----
         This is a simple image-gallery:

        
            
                <img src= "" width="" height="">
            
            <p></p>
         

This relies upon the `FileGlob.pm` behaviour which I'd forgotten about:

* If a glob matches an image __and__ you have Image::Size available then the variables `width` and `height` will be populated.
     * Here we use that to wrap and "if" around the image.
* If the glob __does__ not match an image, and does not match the templer  suffix, then the contents are available as `content` - but this is a bug, becaues the same name is used in the layout.

The files here are:

        deagol ~/x $ ls -1 input/
        17635184_10212309877612942_91544094097573559_o.jpg
        17635184_10212309877612942_91544094097573559_o.jpg.caption
        18278724_10155384183372342_4594716052523220387_o.jpg
        18278724_10155384183372342_4594716052523220387_o.jpg.caption
        index.skx

So the glob here matches "`*.jpg*`" which half the time is an image, and half the time is a caption.

**Comment by skx** [comment]
OK bug fixed - the example above should now work if you update to include the commit I just made, but this is a bit terrible, so you might prefer to write a plugin instead :)

**Comment by gh-4** [comment]
I might have a try at a plugin then, and if I can't make it work try the "terrible" way :)

Thanks for the rapid reply!  I guess I'll close this as it seems a plugin is the "official" way to do it.
